### ISSUE TITLE
Hivesigner migration

### ISSUE THREAD

**Issue by feruzm** [emre/steemconnect-python-client#3]
Hello,

As you may have heard, Steemconnect rebranded/migrated to Hivesigner.

Is there plans to create Hivesigner alternative?

Changes are minimal mostly end points which is single point now to: https://hivesigner.com

**Comment by emre** [comment]
Yes, I'll rebrand the repository when I find time. However, it's possible for Python apps to change the config and move on.

**Comment by emre** [comment]
https://github.com/emre/hivesigner-python-client
