### ISSUE TITLE
steemconnect do not exist enymore

### ISSUE THREAD

**Issue by digital-mine** [emre/steemconnect-python-client#4]
HI there,

thanks for your app, I'm currently testing with hive and it is quite intuitive and simple to deploy.

On steem steemconnect do not exist anymore, but it is possible to use steemlogin.com that is exactly the same thing.

Is it possible to run your app but with steemlogin.com instead of steemconnect?

Just change the urls in the defauls.py file doesn't seem to work

**Comment by digital-mine** [comment]
this is the error i got after the login process is done:

simplejson.errors.JSONDecodeError

**Comment by emre** [comment]
Sorry, this library is not maintained anymore.

Note for the HIVE people, use https://github.com/emre/hivesigner-python-client.
